### ISSUE TITLE
[1.14.4] Badly Compressed Packet (?)

### ISSUE THREAD

**Issue by Gbergz** [raptor4694/StorageDrawersUnlimited#4]
Hello,
I was going to add this to my Modpack, but when i decided to add it to the Server and try to join i was met with an annoying message. 

Disconnect Message: _**"Internal Exception: io.netty.handler.codec.DecoderExcepion: Badly compressed packet - size of 2278425 is alrger than protocol maximum of 2097152"**_
Picture of the disconnect message: [Imgur](https://i.imgur.com/0OXDWHs.png)

As soon as i remove the mod from Server & Client both me and others are able to join again. Weird issue to be honest.

Any ideas? Reply if you wan't logs or anything. I looked through them but didn't find anything, but maybe i'm just looking at the wrong stuff.

**Comment by joe-vettek** [comment]
connectivity ,you need it

**Comment by Gbergz** [comment]
Uh this was 2 years ago now ish.
Heh. Figured that out. Forgot to close. 😅
